#!/bin/sh
# End-to-end tests against real commits in throwaway repos: sh test.sh
set -u

here=$(cd "$(dirname "$0")" && pwd)
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
export XDG_CONFIG_HOME="$tmp/config" GIT_CONFIG_GLOBAL="$tmp/gitconfig" GIT_CONFIG_NOSYSTEM=1
unset ALLOW_AI_ATTRIBUTION GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE

git config --global user.name 'Test Human'
git config --global user.email human@example.com
git config --global commit.gpgsign false
git config --global init.defaultBranch main
sh "$here/install.sh" >/dev/null || exit 1

git init -q "$tmp/repo" && cd "$tmp/repo" || exit 1
git commit -q --allow-empty -m init

fail=0
expect() {
	want=$1 desc=$2
	shift 2
	if "$@" >"$tmp/out" 2>&1; then got=accept; else got=reject; fi
	git reset -q --hard
	if [ "$got" = "$want" ]; then
		echo "ok   $want: $desc"
	else
		echo "FAIL $want: $desc"
		sed 's/^/     /' "$tmp/out"
		fail=1
	fi
}

msg() {
	if [ $# -eq 1 ]; then git commit -q --allow-empty -m "$1"; else git commit -q --allow-empty -m "$1" -m "$2"; fi
}

stage() {
	mkdir -p "$(dirname "$1")"
	printf '%s\n' "$2" >"$1"
	git add "$1" && git commit -q -m "Add $1"
}

for m in \
	'Co-Authored-By: Claude <noreply@example.com>' \
	'Generated with Claude Code' \
	'🤖 Generated with [Claude Code](https://claude.com/claude-code)' \
	'Co-authored-by: Codex <noreply@openai.com>' \
	'Co-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>' \
	'Co-authored-by: GPT-5 <bot@example.com>' \
	'Co-authored-by: gemini-code-assist[bot] <bot@example.com>' \
	'Generated by ChatGPT' \
	'Generated by AI' \
	'AI-assisted' \
	'Assisted by Claude' \
	'Claude-Session: https://claude.ai/code/session_01abc'; do
	expect reject "msg body: $m" msg 'Fix parser' "$m"
done
expect reject 'msg subject: Generated by AI' msg 'Generated by AI'

for m in \
	'Add Claude API integration' \
	'Add Claude API client' \
	'Document GPT inference architecture' \
	'Document LLM inference pipeline' \
	'Fix LLM model loader' \
	'Fix GPT tokenizer implementation' \
	'Update Codex integration tests' \
	'Remove "Generated by AI" badge' \
	'Made with love'; do
	expect accept "msg: $m" msg "$m"
done
for t in \
	'Co-authored-by: Jane Doe <jane@example.com>' \
	'Co-authored-by: Claude Dupont <claude.dupont@example.com>' \
	'Signed-off-by: Jane Doe <jane@example.com>'; do
	expect accept "trailer: $t" msg 'Fix parser' "$t"
done

printf 'Fix parser\n# ------------------------ >8 ------------------------\nGenerated by Claude\n' >"$tmp/scissors"
expect accept 'msg: attribution below scissors line' "$XDG_CONFIG_HOME/git/hooks/commit-msg" "$tmp/scissors"

expect reject 'staged: // Generated by Claude' stage a.c '// Generated by Claude'
expect reject 'staged: # AI-generated' stage a.py '# AI-generated'
expect reject 'staged: <!-- Generated with ChatGPT -->' stage a.html '<!-- Generated with ChatGPT -->'
expect reject 'staged: x = 1  # written by Codex' stage b.py 'x = 1  # written by Codex'
expect reject 'staged: - Generated with Claude Code' stage CHANGELOG.md '- Generated with Claude Code'
expect accept 'staged: client = anthropic.Claude()' stage c.py 'client = anthropic.Claude()'
expect accept 'staged: model = "gpt-4o"' stage d.py 'model = "gpt-4o"'
expect accept 'staged: "Detect AI-generated images"' stage e.py 'label = "Detect AI-generated images"'
expect accept 'staged: # Detect AI-generated images' stage f.py '# Detect AI-generated images in uploads'

stage .gitattributes 'docs/** -ai-attribution-check' >/dev/null
expect accept 'staged: exempt path via .gitattributes' stage docs/x.md 'Generated by Claude'

expect accept 'bypass: ALLOW_AI_ATTRIBUTION=1' env ALLOW_AI_ATTRIBUTION=1 git commit -q --allow-empty -m 'Generated by AI'
expect accept 'bypass: --no-verify' git commit -q --no-verify --allow-empty -m 'Generated by AI'

msg 'Identity check'
id=$(git log -1 --format='%an <%ae>|%cn <%ce>')
expect accept 'identity unchanged' test "$id" = 'Test Human <human@example.com>|Test Human <human@example.com>'

printf '#!/bin/sh\ntouch "%s/local-pre-commit"\n' "$tmp" >.git/hooks/pre-commit
chmod +x .git/hooks/pre-commit
expect accept 'chain: local pre-commit runs' msg 'Chain'
expect accept 'chain: local pre-commit ran' test -e "$tmp/local-pre-commit"
printf '#!/bin/sh\nexit 1\n' >.git/hooks/pre-commit
expect reject 'chain: failing local pre-commit blocks' msg 'Chain'
rm .git/hooks/pre-commit

git init -q --bare "$tmp/remote.git"
printf '#!/bin/sh\ncat >/dev/null\ntouch "%s/local-pre-push"\n' "$tmp" >.git/hooks/pre-push
chmod +x .git/hooks/pre-push
expect accept 'chain: push' git push -q "$tmp/remote.git" HEAD:main
expect accept 'chain: local pre-push ran' test -e "$tmp/local-pre-push"

sh "$here/install.sh" --uninstall >/dev/null
expect accept 'uninstall: core.hooksPath unset' test -z "$(git config --global --get core.hooksPath)"
expect accept 'uninstall: hooks removed' test ! -e "$XDG_CONFIG_HOME/git/hooks"

[ "$fail" = 0 ] && echo "all passed"
exit "$fail"
